### PR TITLE
Fix hdf5 imports in `deployment/check-environment.sh`

### LINKED ISSUE #59: Failure & coredump `check-environment.sh` using `blosc` filter
On my local system, after installing `conda` & building the environment as per the README. Running `deployment/check-environment.sh` failed here:

https://github.com/OpenDataCubePipelines/ard-pipeline/blob/ea84164ab0cd4fb13188984bfd4332d7eb6b59e1/deployment/check-environment.sh#L55

The output:

```Bash
# ... other tests passing

Attempting hdf5 blosc compression...python3: /home/conda/feedstock_root/build_artifacts/libnetcdf_1702228817425/work/plugins/H5Zblosc.c:160: blosc_set_local: Assertion `nelements == 7' failed.
./ard-pipeline/deployment/check-environment.sh: line 63: 121505 Aborted                 (core dumped) python3 <<EOF

# rest of embedded python code printed to terminal
```

Modifying `check-environment.sh`'s embedded python to use `hdf5plugin` directly solves the core dump:

```Python
# The previous import of wagl should have initialised the filters.
print("Attempting hdf5 blosc compression...", end='', flush=True)
import h5py
import hdf5plugin  # for filter plugins
import tempfile
f = h5py.File(tempfile.mktemp('-test.h5'),'w')

# FIX: change compression from int to a plugin
dset = f.create_dataset("myData", (100, 100), compression=hdf5plugin.Blosc())
```

### PR DESCRIPTION
**Pull request by truth-quark**
Closes #59.

This PR switches `deployment/check-environment.sh` to use filter objects instead of int codes. This is an attempt to prevent core dump crashes on some platforms that cannot handle int codes as the `compression=...` option.

Also added, a second check in the script to build a hdf5 dataset using default options.

I've also added a TODO to check if importing `wagl` actually initialises the filters. This was failing in some cases.

### CODE REVIEW

**Comment by truth-quark** [comment]
As the `wagl` workflow doesn't use Blosc compression, can we remove Blosc from `check-environment.sh`?

File: deployment/check-environment.sh [hunk 1]
```diff
@@ -47,12 +47,28 @@ print("Attempting load of fortran-based modules... ", end='', flush=True)
...
 import h5py
+import hdf5plugin
 import tempfile
+
+# Test different forms of compression usage as per the hdf5plugin docs:
+# https://hdf5plugin.readthedocs.io/en/stable/usage.html
+# use "hdf5plugin.Blosc()" style instead of int code to prevent crashes
+print("Attempting hdf5 blosc compression...", end='', flush=True)
 f = h5py.File(tempfile.mktemp('-test.h5'),'w')
-dset = f.create_dataset("myData", (100, 100), compression=32001)
```
Comment (sixy6e) [inline deployment/check-environment.sh:55]: I don't know who created this test, but it will never work, as blosc requires additional `compression_opts` to be passed through in the form of a tuple of 7 integers, eg `(0, 0, 0, 0, 9, 1, 5)`

File: deployment/check-environment.sh [hunk 2]
```diff
@@ -47,12 +47,28 @@ print("Attempting load of fortran-based modules... ", end='', flush=True)
...
+dset = f.create_dataset("myData", (100, 100), compression=hdf5plugin.Blosc())
```
Comment (sixy6e) [inline deployment/check-environment.sh:61]: I do recommend using wagl's compression config to generate the required kwargs.

```python
from wagl import hdf5
comp = hdf5.compression.H5CompressionFilter.BLOSC_ZSTANDARD
config = comp.config(chunks=(200, 300), aggression=9)
kwargs = config.dataset_compression_kwargs()
# print(kwargs)  to actually see what it comes back as
# {'chunks': (200, 300), 'shuffle': False, 'compression': 32001, 'compression_opts': (0, 0, 0, 0, 9, 1, 5)}

Comment (sixy6e) [reply deployment/check-environment.sh:61]: this would then test that the plugin is available, and that the wagl config generator is doing it correctly.

Comment (truth-quark) [reply deployment/check-environment.sh]: I've shrunk the script down to replace the old int codes with a single test case using the wagl's specific config in [b02d4d4](https://github.com/OpenDataCubePipelines/ard-pipeline/pull/69/commits/b02d4d415739926487b6e701c0b60b51aa98790d).

The `check-environment` script:
* Ran on my local machine (only failed on to find modtran, as expected)
* Passed on `gadi`.

**Comment by sixy6e** [comment]
Looks good:

```bash
Checking environment...
Trying rasterio... __ 1.3.9
Trying luigi... __ 3.5.0
Trying wagl... __ 6.1.2.dev22+gb02d4d41
Attempting load of fortran-based modules... __
Attempting hdf5 blosc compression...__
Checking modtran is available...__
```

**Review by sixy6e — APPROVED** [review]
:+1:

**Comment by truth-quark** [comment]
> Looks good:
> 
> ```shell
> Checking environment...
<snip>
> Checking modtran is available...__
> ```

I am wondering if the output green emoji tick characters are a good idea...
